# Generated by Django 3.2.9 on 2021-12-04 17:42

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_name', models.CharField(max_length=255)),
                ('fur_pattern', models.CharField(choices=[('Tabby', 'Tabby'), ('Solid', 'Solid'), ('Bicolor', 'Bicolor'), ('Tortoiseshell', 'Tortoiseshell'), ('Colorpoint', 'Colorpoint')], default='', max_length=15)),
                ('fur_color', models.CharField(default='unknown', max_length=255)),
                ('fur_length', models.CharField(choices=[('Long', 'Long'), ('Short', 'Short'), ('Curly', 'Curly'), ('Hairless', 'Hairless')], max_length=15)),
                ('age', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sex', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Unknown', 'Unknown')], max_length=15)),
                ('location', models.CharField(choices=[('Tallinn', 'Tallinn'), ('Tartu', 'Tartu'), ('Rakvere', 'Rakvere'), ('Narva', 'Narva'), ('Sillamae', 'Sillamäe'), ('Kuuresaare', 'Kuuresaare'), ('Haapsalu', 'Haapsalu'), ('Parnu', 'Pärnu'), ('Kohtla-jarve', 'Kohtla-Järve'), ('Valga', 'Valga'), ('Polva', 'Põlva'), ('Toila', 'Toila'), ('EU', 'EU'), ('Estonia', 'Estonia'), ('Non-EU', 'Non-EU')], max_length=15)),
                ('description', models.TextField(blank=True)),
                ('special_needs', models.TextField(blank=True)),
                ('image', models.ImageField(default='images/default.jpg', upload_to='images/')),
                ('slug', models.SlugField(max_length=255)),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(15.0)])),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animal', to='store.category')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animal_creator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Animals',
                'ordering': ('-created',),
            },
        ),
    ]
