# Generated by Django 3.2.9 on 2021-11-20 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='fur_pattern',
            field=models.CharField(choices=[('t', 'Tabby'), ('s', 'Solid'), ('b', 'Bicolor'), ('t', 'Tortoiseshell'), ('c', 'Colorpoint')], default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='animal',
            name='fur_length',
            field=models.CharField(choices=[('l', 'Long'), ('s', 'Short'), ('c', 'Curly'), ('h', 'Hairless')], max_length=1),
        ),
        migrations.AlterField(
            model_name='animal',
            name='sex',
            field=models.CharField(choices=[('f', 'Female'), ('m', 'Male'), ('u', 'Unknown')], max_length=1),
        ),
    ]
