# Generated by Django 3.2.9 on 2021-11-20 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20211120_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='age',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='animal',
            name='fur_length',
            field=models.CharField(choices=[('Long', 'Long'), ('Short', 'Short'), ('Curly', 'Curly'), ('Hairless', 'Hairless')], max_length=15),
        ),
        migrations.AlterField(
            model_name='animal',
            name='fur_pattern',
            field=models.CharField(choices=[('Tabby', 'Tabby'), ('Solid', 'Solid'), ('Bicolor', 'Bicolor'), ('Tortoiseshell', 'Tortoiseshell'), ('Colorpoint', 'Colorpoint')], default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='animal',
            name='location',
            field=models.CharField(choices=[('Tallinn', 'Tallinn'), ('Tartu', 'Tartu'), ('Rakvere', 'Rakvere'), ('Narva', 'Narva'), ('Sillamae', 'Sillamäe'), ('Kuuresaare', 'Kuuresaare'), ('Haapsalu', 'Haapsalu'), ('Parnu', 'Pärnu'), ('Kohtla-jarve', 'Kohtla-Järve'), ('Valga', 'Valga'), ('Polva', 'Põlva'), ('Toila', 'Toila'), ('EU', 'EU'), ('Estonia', 'Estonia'), ('Non-EU', 'Non-EU')], max_length=15),
        ),
        migrations.AlterField(
            model_name='animal',
            name='sex',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Unknown', 'Unknown')], max_length=15),
        ),
    ]
