# Generated by Django 3.2.9 on 2021-11-21 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20211120_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='age',
            field=models.DecimalField(decimal_places=2, default='', max_digits=5),
        ),
    ]
