# Generated by Django 3.2.9 on 2021-11-21 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_animal_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='age',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=5),
        ),
    ]
