# Generated by Django 3.2.9 on 2021-12-04 07:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0009_alter_animal_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animal', to='store.category'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animal_creator', to=settings.AUTH_USER_MODEL),
        ),
    ]
